### ISSUE TITLE
反编译出来类名是a,b,c

### ISSUE THREAD

**Issue by lxsyz** [ufologist/onekey-decompile-apk#1]
反编译出来后类名仍是a,b,c，是因为别人混淆过的原因吗
在反编译过程中，could not decode arges file 报错是什么原因呢

**Comment by ufologist** [comment]
如何别人已经混淆过的代码, 你是没有办法反混淆的, 因此反编译过来还是得到的 a, b, c 这样的内容.

至于反编译过程中为什么报错"could not decode arges file", 请说明是哪一步出错了, 因为项目只是集成了其他成熟的工具, 因此请搜索相关的工具来查找错误和解决的办法.

具体使用了哪些工具请参考 [_tools 目录](https://github.com/ufologist/onekey-decompile-apk/tree/master/onekey-decompile-apk/_tools)
