### ISSUE TITLE
可以写一个支持linux/mac 下面的shell 脚本吗？

### ISSUE THREAD

**Issue by xwEric** [ufologist/onekey-decompile-apk#2]
可以写一个支持linux/mac 下面的shell 脚本吗？

**Comment by ufologist** [comment]
由于我一直使用的是 Windows 系统, 所以这个脚本都是针对 Windows 的.
不过脚本都很简单, 推荐你自己 fork 出一个 Linux 版本的, 只需要将脚本里面对应的 Windows 系统下面的操作换成 Linux 的即可, 例如设置环境变量...

对于这个脚本的 Linux 版本支持, 可能要等到我换到 Linux 系统工作了吧, 因为现在这个东西对我来说够用了, 开源出来了, 大家可以根据自己的需要修改.

**Comment by venshine** [comment]
@HuaWeng https://github.com/venshine/decompile-apk
